/*
 * KIV-DS 01 sequencer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patrikharag@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cz.harag.ds.cv01.client.sequencer.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
