swagger: '2.0'
info:
  version: 1.0.0
  title: KIV-DS 01 sequencer
  contact:
    email: patrikharag@gmail.com

paths:
  /sequencer:
    post:
      summary: Accepts financial operation
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: operation
        description: Financial operation to perform
        schema:
          $ref: '#/definitions/operation'
      responses:
        201:
          description: Accepted
        401:
          description: Invalid input, object invalid

definitions:
  operation:
    type: object
    required:
    - value
    properties:
      value:
        type: integer
        format: int32
        example: 2599