Vagrant.configure("2") do |config|

    config.vm.define "bank1" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.3.61"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8081 *:8091,*:8092 10.0.3.62:8093,10.0.3.64:8098 1>log-server-1.txt 2>&1 &
            
        SHELL
    end
    
    config.vm.define "bank2" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.3.62"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8082 *:8093,*:8094,*:8100 10.0.3.61:8091,10.0.3.63:8095,10.0.3.64:8099 1>log-server-2.txt 2>&1 &
            
        SHELL
    end
    
    config.vm.define "bank3" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.3.63"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8083 *:8095,*:8096 10.0.3.62:8094,10.0.3.64:8097 1>log-server-3.txt 2>&1 &
            
        SHELL
    end
    
    config.vm.define "bank4" do |cfg|
        cfg.vm.box = "geerlingguy/centos7"
        cfg.vm.network "private_network", ip: "10.0.3.64"
        cfg.vm.provision "shell", inline: <<-SHELL
            yum -q -y install java-1.8.0-openjdk
            java -version
            
            cd /vagrant
            nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8084 *:8097,*:8098,*:8099 10.0.3.63:8096,10.0.3.61:8092,10.0.3.62:8100 1>log-server-4.txt 2>&1 &
            
        SHELL
    end
  
end

# nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8081 *:8091,*:8092 10.0.3.62:8093,10.0.3.64:8098 1>log-server-1.txt 2>&1 &
# nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8082 *:8093,*:8094,*:8100 10.0.3.61:8091,10.0.3.63:8095,10.0.3.64:8099 1>log-server-2.txt 2>&1 &
# nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8083 *:8095,*:8096 10.0.3.62:8094,10.0.3.64:8097 1>log-server-3.txt 2>&1 &
# nohup java -jar target/server-1.0.0-SNAPSHOT.jar 8084 *:8097,*:8098,*:8099 10.0.3.63:8096,10.0.3.61:8092,10.0.3.62:8100 1>log-server-4.txt 2>&1 &
