CREATE OR REPLACE VIEW VITEZOVE AS
    SELECT h.ID, o.RADKY, o.SLOUPCE, o.MINY,
            (h.POSLEDNI_TAH - h.PRVNI_TAH) AS TRVANI
    FROM HRA h
    INNER JOIN OBLAST o ON h.OBLAST_ID = o.ID
    WHERE h.STAV_ID = 2
    ORDER BY (h.POSLEDNI_TAH - h.PRVNI_TAH);