@startuml
title Session (client view)

[*] --> connected

state "Connected" as connected
connected --> logged:LIN
connected --> not_connected:BYE,\nerror

state "Logged" as logged
logged --> not_connected:BYE,\nerror
logged --> game:GJO
logged --> logged:GLI,\nGNW
logged --> connected:LOF

state "In game" as game
game --> not_connected:BYE,\nerror
game --> logged:GOF
game --> game:GAC,\nGST, GPL

state "Disconnected" as not_connected
not_connected --> [*]
@enduml
