/*
 * KIV-DS 01 server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: patrikharag@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package cz.harag.ds.cv01.client.server.api;

import cz.harag.ds.cv01.client.server.ApiException;
import cz.harag.ds.cv01.client.server.model.Operation;

import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Accepts financial operation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void shufflerPostTest() throws ApiException {
        Operation operation = null;
        api.serverPost(operation);

        // TODO: test validations
    }
    
}
